INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (80, 'wewe', '12', 'sdfdsfffsfdsfsdfsdfsd', '5b94171e55245.jpg', null);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (81, '11', '22', '33', '5b941c1ea847c.jpg', null);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (82, 'wewe', '2', 'sdsdsdsd', '5b941deaeb44b.', null);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (83, 'wewe', '12', '1212212', '5b94e0778b02a.jpg', 1);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (84, 'Stanislav Dimitrenco', '222', '123', '5b94e1d0cd323.jpg', 1);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (85, 'wewe', '2', '2323432', '5b94e4b3867ac.', 2);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (86, '1', '22', '1231233', '5b94e7e43da16.jpg', 36);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (87, '1', '3455', 'dfdsfsdfsdf', '5b94e8004686e.jpg', 36);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (88, '2', '33', '12344', '5b94e82ad15e0.jpg', 37);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (89, '6', '66', '343434', '5b94e8550b8ae.jpg', 41);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (90, '1', '22', '2323232', '5b94e91dcdfa3.', 36);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (91, '', '', '', '', null);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (92, 'Stas', '23', '23232', '5b94ebf315aa3.', 42);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (93, 'Stas', '123', '123', '5b94ec7a54b23.', 42);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (139, 'Garland Herman', '25', 'Sapiente accusamus magnam ut saepe assumenda hic. Explicabo sit quibusdam cum aspernatur eum non eius voluptatem. Rem molestiae et sit odit sint facilis.', 'https://lorempixel.com/640/480/?26768', 0);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (140, 'Sterling Pouros', '28', 'Qui rerum perferendis ipsum. Ea aspernatur dolore quas suscipit vel voluptas. Hic quasi qui minus molestias aliquid doloremque quod.', 'https://lorempixel.com/640/480/?78178', 1);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (151, 'Kayleigh McKenzie II', '24', 'Error sit at blanditiis ut. Quia repellat ea soluta eum ut minus voluptatem.', 'https://lorempixel.com/640/480/?28203', 4);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (152, 'Bobby Watsica', '24', 'Rerum ut ut ratione nihil qui. Quod optio molestiae magni ut voluptatem non et. Maxime est dignissimos ut.', 'https://lorempixel.com/640/480/?73959', 1);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (153, 'Irwin Gislason DVM', '25', 'Assumenda voluptatum qui eveniet provident. Ex veritatis ipsum voluptatem qui doloribus a. Laborum iusto velit cupiditate cumque animi ducimus.', 'https://lorempixel.com/640/480/?10939', 10);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (154, 'Prof. Dean Langosh PhD', '28', 'Ratione numquam dolorem ducimus rem ut delectus. Aut explicabo molestias perspiciatis suscipit qui corrupti rerum illo. Incidunt dolore quisquam similique perferendis.', 'https://lorempixel.com/640/480/?47869', 8);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (155, 'Trenton Kuvalis', '20', 'Commodi vitae libero quia. Ut illum et provident natus maiores dolor. Quae dolorem dolorum iusto necessitatibus sed. Non adipisci neque rerum. Voluptate rerum a ex.', 'https://lorempixel.com/640/480/?89882', 5);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (156, 'Justen Zboncak', '20', 'Voluptatem ea omnis expedita odit. Autem officiis molestiae fuga quia. Dicta odit pariatur nemo exercitationem sequi deserunt. Ut eum aspernatur maiores est. Totam soluta dolor dolorem saepe.', 'https://lorempixel.com/640/480/?91197', 6);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (157, 'Dr. Jayden Kunze DVM', '27', 'Provident soluta nostrum ut et ut. Sit consequatur facilis ullam ea non. Doloribus qui id dolores sit.', 'https://lorempixel.com/640/480/?43085', 3);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (158, 'Ulices Durgan II', '28', 'Temporibus deserunt nisi reprehenderit vero quis iusto. Error est autem fuga sed maiores eaque ea blanditiis. Et repellendus rerum facilis possimus dolor quia.', 'https://lorempixel.com/640/480/?75372', 7);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (159, 'Blaise Breitenberg', '25', 'Qui nihil dolores deleniti quis et. Consequatur impedit autem dolor fuga voluptatem.', 'https://lorempixel.com/640/480/?89710', 2);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (160, 'Fernando Lindgren', '24', 'Voluptatem sed repellendus exercitationem dolorem maiores. Expedita saepe tempora eum qui. Hic ex veritatis est nemo.', 'https://lorempixel.com/640/480/?42246', 6);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (161, '1', '23', '123', '5b96a21acef98.jpg', 36);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (162, '1', '2', 'qweqwew', '5b96a5ea6f3c5.', 36);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (163, '1', '2', '12sadsadasdas', '5b96a5ffec185.', 36);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (164, '1111111', '12', 'ываывавыаыыа', '5b96a80687536.', 36);
INSERT INTO mvc.lists (id, name, years, text, url, userId) VALUES (165, '1', '23', 'rererererrere', '5b976a20e2d6d.jpg', 36);